services:
  # Backend Service
  - type: web
    name: barber-queue-backend
    runtime: node
    rootDirectory: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true

  # Frontend Service
  - type: static
    name: barber-queue-frontend
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    publishDirectory: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://barber-queue-backend.onrender.com

databases:
  - name: barber-db
    databaseName: barberdb
    user: barber 